#arthmeti  opertors
nambari=int(input("enter the first number"))
namberi2=int(input("enter the second number"))
print(nambari+namberi2)
print(nambari-namberi2)
print(nambari*namberi2)
print(nambari/namberi2)
print(nambari%namberi2)
# comparison operator
nambari3=int(input("enter the first number :"))
nambari4=int(input("enter the second number :"))
print(f"{nambari3}is equal to {nambari4} : {nambari3==nambari4}")
print(f"{nambari3}is not equal to {nambari4} : {nambari3!=nambari4}")
print(f"{nambari3} is greater tnan {nambari4} : {nambari3 > nambari4}")
print(f"{nambari3} is less than {nambari4} : {nambari3 < nambari4}")
print(f"{nambari3}is equal to {nambari4} : {nambari3==nambari4}")
print(f"{nambari3}is less than or equal to {nambari4} : {nambari3 <= nambari4}")
# logical operator
nambari5=int(input("bonyeza numbari:"))
nambari6=int("bonyeza ya pili")
print(f"both statements should be true :{nambari5==6 and nambari5>nambari6}")
print(f"one statement should be true :{nambari5==6 or nambari5 >nambari6}")